apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: node-server
          image: node-server:v1
        ports:
        - containerPort: 3000
